"""empty message

Revision ID: 035d86485875
Revises: af3af52ef48c
Create Date: 2021-10-25 14:48:58.798456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035d86485875'
down_revision = 'af3af52ef48c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'own')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('own', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
