"""empty message

Revision ID: 0865797c0bab
Revises: c71f61ca7567
Create Date: 2021-12-09 09:57:57.445196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0865797c0bab'
down_revision = 'c71f61ca7567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bundles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bundle_items',
    sa.Column('bundles_id', sa.Integer(), nullable=True),
    sa.Column('product_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bundles_id'], ['bundles.id'], ),
    sa.ForeignKeyConstraint(['product_item_id'], ['product_item.id'], )
    )
    op.add_column('product_item', sa.Column('bundle_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product_item', 'bundles', ['bundle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_item', type_='foreignkey')
    op.drop_column('product_item', 'bundle_id')
    op.drop_table('bundle_items')
    op.drop_table('bundles')
    # ### end Alembic commands ###
