"""empty message

Revision ID: 0da15022a0f9
Revises: 208beab88526
Create Date: 2021-11-24 10:10:15.949716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da15022a0f9'
down_revision = '208beab88526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_places', sa.Column('name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_places', 'name')
    # ### end Alembic commands ###
