"""empty message

Revision ID: 10f543d6a818
Revises: 118837730e47
Create Date: 2021-11-06 12:22:51.067554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10f543d6a818'
down_revision = '118837730e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_item', sa.Column('special_license', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_item', 'special_license')
    # ### end Alembic commands ###
