"""empty message

Revision ID: 118837730e47
Revises: c3dd7cd72b3c
Create Date: 2021-11-05 17:59:26.307302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118837730e47'
down_revision = 'c3dd7cd72b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('personal_price_cents', sa.Integer(), nullable=True),
    sa.Column('commercial_price_cents', sa.Integer(), nullable=True),
    sa.Column('extended_price_cents', sa.Integer(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_item')
    # ### end Alembic commands ###
