"""empty message

Revision ID: 208beab88526
Revises: cc37155ccb6d
Create Date: 2021-11-18 21:16:37.518193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208beab88526'
down_revision = 'cc37155ccb6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_item', sa.Column('name', sa.Text(), nullable=True))
    op.add_column('sales', sa.Column('product_item_id', sa.Integer(), nullable=True))
    op.drop_constraint('sales_market_place_id_fkey', 'sales', type_='foreignkey')
    op.drop_constraint('sales_account_id_fkey', 'sales', type_='foreignkey')
    op.drop_constraint('sales_product_id_fkey', 'sales', type_='foreignkey')
    op.create_foreign_key(None, 'sales', 'product_item', ['product_item_id'], ['id'])
    op.drop_column('sales', 'product_id')
    op.drop_column('sales', 'market_place_id')
    op.drop_column('sales', 'account_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sales', sa.Column('market_place_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sales', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.create_foreign_key('sales_product_id_fkey', 'sales', 'products', ['product_id'], ['id'])
    op.create_foreign_key('sales_account_id_fkey', 'sales', 'accounts', ['account_id'], ['id'])
    op.create_foreign_key('sales_market_place_id_fkey', 'sales', 'market_places', ['market_place_id'], ['id'])
    op.drop_column('sales', 'product_item_id')
    op.drop_column('product_item', 'name')
    # ### end Alembic commands ###
