"""empty message

Revision ID: 249489a299ea
Revises: d115eaa15de3
Create Date: 2021-12-15 22:20:41.986467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249489a299ea'
down_revision = 'd115eaa15de3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bundle_items')
    op.drop_table('bundles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bundles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('bundles_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='bundles_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('bundle_items',
    sa.Column('bundles_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bundles_id'], ['bundles.id'], name='bundle_items_bundles_id_fkey'),
    sa.ForeignKeyConstraint(['product_item_id'], ['product_item.id'], name='bundle_items_product_item_id_fkey')
    )
    # ### end Alembic commands ###
