"""empty message

Revision ID: 26d270747ab9
Revises: 249489a299ea
Create Date: 2021-12-15 22:23:19.728555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26d270747ab9'
down_revision = '249489a299ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_bundle', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_bundle')
    # ### end Alembic commands ###
