"""empty message

Revision ID: 613c6d8b8a49
Revises: e1a503a0d9e1
Create Date: 2021-10-25 09:51:16.794939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613c6d8b8a49'
down_revision = 'e1a503a0d9e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('market_place_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales', 'market_places', ['market_place_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'market_place_id')
    # ### end Alembic commands ###
