"""empty message

Revision ID: af3af52ef48c
Revises: 613c6d8b8a49
Create Date: 2021-10-25 14:29:56.860456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af3af52ef48c'
down_revision = '613c6d8b8a49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
