"""empty message

Revision ID: c3dd7cd72b3c
Revises: ee36e5a2bc72
Create Date: 2021-10-27 16:20:30.038100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3dd7cd72b3c'
down_revision = 'ee36e5a2bc72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
