"""empty message

Revision ID: cc37155ccb6d
Revises: 10f543d6a818
Create Date: 2021-11-06 13:00:50.627427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc37155ccb6d'
down_revision = '10f543d6a818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_item', sa.Column('is_live', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_item', 'is_live')
    # ### end Alembic commands ###
