"""empty message

Revision ID: d115eaa15de3
Revises: 0865797c0bab
Create Date: 2021-12-15 22:19:55.913956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd115eaa15de3'
down_revision = '0865797c0bab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_item_bundle_id_fkey', 'product_item', type_='foreignkey')
    op.drop_column('product_item', 'bundle_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_item', sa.Column('bundle_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('product_item_bundle_id_fkey', 'product_item', 'bundles', ['bundle_id'], ['id'])
    # ### end Alembic commands ###
