"""empty message

Revision ID: e1a503a0d9e1
Revises: 2d98ac3de267
Create Date: 2021-10-24 18:04:19.022160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a503a0d9e1'
down_revision = '2d98ac3de267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('own', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('market_place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['market_place_id'], ['market_places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('earning_cents', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cookies', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cookies', 'accounts', ['account_id'], ['id'])
    op.drop_column('cookies', 'username')
    op.drop_column('cookies', 'domain')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cookies', sa.Column('domain', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('cookies', sa.Column('username', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cookies', type_='foreignkey')
    op.drop_column('cookies', 'account_id')
    op.drop_table('sales')
    op.drop_table('accounts')
    op.drop_table('products')
    op.drop_table('market_places')
    # ### end Alembic commands ###
