"""empty message

Revision ID: ee36e5a2bc72
Revises: 035d86485875
Create Date: 2021-10-26 14:43:48.737973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee36e5a2bc72'
down_revision = '035d86485875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'account_id')
    # ### end Alembic commands ###
